repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        name: terraform docs for the 'instance' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/instance"]
      - id: terraform-docs-go
        name: terraform docs for the 'scanning-delegate-role' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/scanning-delegate-role"]
      - id: terraform-docs-go
        name: terraform docs for the 'side-scanner-role' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/side-scanner-role"]
      - id: terraform-docs-go
        name: terraform docs for the 'user_data' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/user_data"]
      - id: terraform-docs-go
        name: terraform docs for the 'vpc' module
        args: ["markdown", "table", "--output-file", "README.md", "./modules/vpc"]
  
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.83.6"
    hooks:
      - id: terraform_fmt
        name: terraform fmt
        args: [--args=-recursive]
      - id: terraform_tflint
        name: terraform lint
        args: [--args=--disable-rule=terraform_module_pinned_source]